NAME=proj3
do: $(NAME).tex
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex
clean:
	rm $(NAME).aux $(NAME).log $(NAME).pdf etiopan-eps-converted-to.pdf oniisan-eps-converted-to.pdf oniisan2-eps-converted-to.pdf
